[build]
  publish = "dist/public"
  command = "npm run build:static"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev:static"
  port = 3000
  publish = "dist/public"